[package]
name = "ruten-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
jsonwebtoken = "8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }