[package]
name = "ruten-api"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "1.3.18"
poem-openapi = "1.3.18"
ruten-shared = { path = "../ruten-shared" }
tokio = { version = "1", features = ["full"] }